(function () {
'use strict';

function null_undefined_to_opt(x) {
  if (x === null || x === undefined) {
    return /* None */0;
  } else {
    return /* Some */[x];
  }
}


/* No side effect */

// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
function get_header(name, req) {
  return null_undefined_to_opt(req.headers.get(name));
}

function accepts(mime, req) {
  var match = get_header("accept", req);
  if (match) {
    return +match[0].includes(mime);
  } else {
    return /* false */0;
  }
}

function is_jpeg(req) {
  return +(/\.jpe?g$/).test(req.url);
}

function replace_ext(url, ext) {
  var idx = url.lastIndexOf(".");
  return url.substring(0, idx) + ("." + ext);
}

self.onfetch = function (evt) {
  var req = evt.request;
  if (is_jpeg(req) && accepts("webp", req)) {
    var url = replace_ext(req.url, "webp");
    evt.respondWith(fetch(url, {
              mode: "no-cors"
            }));
    return /* () */0;
  } else {
    return 0;
  }
};


/*  Not a pure module */

}());
