(function () {
'use strict';

function is_nil_undef(x) {
  if (x === null) {
    return /* true */1;
  } else {
    return +(x === undefined);
  }
}


/* No side effect */

// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
function accepts(mime, req) {
  var match = req.headers.get("accept");
  if (is_nil_undef(match)) {
    return /* false */0;
  } else {
    return +match.includes(mime);
  }
}

var jpeg_ext_re = (/\.jpe?g$/);

function response(req) {
  var url = req.url;
  return caches.match(req).then(function (x) {
              if (is_nil_undef(x)) {
                if (jpeg_ext_re.test(url) && accepts("webp", req)) {
                  return fetch(url.replace(jpeg_ext_re, ".webp"), {
                              mode: "no-cors"
                            });
                } else {
                  return fetch(req);
                }
              } else {
                return Promise.resolve(x);
              }
            });
}

self.onfetch = function (evt) {
  evt.respondWith(response(evt.request));
  return /* () */0;
};


/* jpeg_ext_re Not a pure module */

}());
