// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

function accepts(mime, req) {
  var match = req.headers.get("accept");
  if (Js_primitive.is_nil_undef(match)) {
    return /* false */0;
  } else {
    return +match.includes(mime);
  }
}

var jpeg_ext_re = (/\.jpe?g$/);

self.onfetch = function (evt) {
  var req = evt.request;
  var url = req.url;
  if (jpeg_ext_re.test(url) && accepts("webp", req)) {
    evt.respondWith(fetch(url.replace(jpeg_ext_re, ".webp"), {
              mode: "no-cors"
            }));
    return /* () */0;
  } else {
    return 0;
  }
};

export {
  
}
/* jpeg_ext_re Not a pure module */
