// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

function get_header(name, req) {
  return Js_primitive.null_undefined_to_opt(req.headers.get(name));
}

function accepts(mime, req) {
  var match = get_header("accept", req);
  if (match) {
    return +match[0].includes(mime);
  } else {
    return /* false */0;
  }
}

function is_jpeg(req) {
  return +(/\.jpe?g$/).test(req.url);
}

function replace_ext(url, ext) {
  var idx = url.lastIndexOf(".");
  return url.substring(0, idx) + ("." + ext);
}

self.onfetch = function (evt) {
  var req = evt.request;
  if (is_jpeg(req) && accepts("webp", req)) {
    var url = replace_ext(req.url, "webp");
    evt.respondWith(fetch(url, {
              mode: "no-cors"
            }));
    return /* () */0;
  } else {
    return 0;
  }
};

export {
  
}
/*  Not a pure module */
