#!/bin/sh

# Avoid nonsense in emacs buffer
export NPM_CONFIG_COLOR=false

# Prompt to commit sw.js build target if changed
if [ -n "$(git diff-index HEAD sw.js)" ]; then
    git add sw.js
    git commit -a
fi
